#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "${SCRIPT_DIR}/_common.sh"

SHARED_ROOT="${CHALLENGE_SHARED_ROOT:-}"
ENV_NAME="${CHALLENGE_ENV_NAME:-lingbotvla}"
MIN_FREE_GB="${CHALLENGE_MIN_FREE_GB:-100}"
INSTALL_ENV=0
FLASH_ATTN_WHEEL=""
CONDA_SH="${CHALLENGE_CONDA_SH:-}"

usage() {
  cat <<'USAGE'
Usage: bash scripts/challenge/bootstrap.sh --shared-root PATH [options]

Prepare a persistent shared-disk layout and write .challenge.env. This script
does not download model weights or datasets. Use fetch_whitelist.sh afterwards;
it is intentionally limited to the competition-approved repositories/files.

Options:
  --shared-root PATH        Persistent/shared disk mount (required once)
  --env-name NAME           Conda environment name (default: lingbotvla)
  --min-free-gb N           Minimum free space required (default: 100)
  --install-env             Install the pinned Python environment (network use)
  --flash-attn-wheel PATH   Local flash-attn wheel passed to the env installer
  --conda-sh PATH           conda.sh path (auto-detected from conda by default)
  -h, --help                Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --shared-root) SHARED_ROOT="${2:?--shared-root requires a path}"; shift 2 ;;
    --env-name) ENV_NAME="${2:?--env-name requires a name}"; shift 2 ;;
    --min-free-gb) MIN_FREE_GB="${2:?--min-free-gb requires an integer}"; shift 2 ;;
    --install-env) INSTALL_ENV=1; shift ;;
    --flash-attn-wheel) FLASH_ATTN_WHEEL="${2:?--flash-attn-wheel requires a path}"; shift 2 ;;
    --conda-sh) CONDA_SH="${2:?--conda-sh requires a path}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) challenge_die "Unknown argument: $1" ;;
  esac
done

[[ -n "${SHARED_ROOT}" ]] || { usage >&2; challenge_die '--shared-root is required.'; }
[[ "${MIN_FREE_GB}" =~ ^[0-9]+$ ]] || challenge_die '--min-free-gb must be a non-negative integer.'
[[ "${ENV_NAME}" =~ ^[A-Za-z0-9._-]+$ ]] || challenge_die 'Unsafe conda environment name.'
if [[ -z "${CONDA_SH}" ]]; then
  command -v conda >/dev/null 2>&1 || \
    challenge_die 'conda is unavailable; pass --conda-sh /absolute/path/to/conda.sh.'
  CONDA_SH="$(conda info --base)/etc/profile.d/conda.sh"
fi
[[ -f "${CONDA_SH}" ]] || challenge_die "conda.sh not found: ${CONDA_SH}"

mkdir -p "${SHARED_ROOT}"
SHARED_ROOT="$(challenge_realpath "${SHARED_ROOT}")"
REPO_ROOT="$(challenge_repo_root)"

[[ "${SHARED_ROOT}" != / ]] || challenge_die 'Refusing to use / as the shared root.'
[[ "${SHARED_ROOT}" != "$(challenge_realpath "${HOME}")" ]] || challenge_die 'Refusing to use the home directory as the shared root.'
[[ "${SHARED_ROOT}" != "${REPO_ROOT}" ]] || challenge_die 'Use a dedicated shared directory, not the Git checkout.'
[[ -w "${SHARED_ROOT}" ]] || challenge_die "Shared root is not writable: ${SHARED_ROOT}"

free_kb="$(df -Pk "${SHARED_ROOT}" | awk 'NR==2 {print $4}')"
required_kb=$((MIN_FREE_GB * 1024 * 1024))
(( free_kb >= required_kb )) || challenge_die "Shared disk has less than ${MIN_FREE_GB} GiB free."

for directory in \
  cache/huggingface/hub cache/huggingface/datasets cache/huggingface/assets \
  cache/huggingface/xet cache/huggingface/transformers cache/torch cache/pip \
  cache/xdg cache/pycache cache/conda/pkgs tmp models data/train \
  data/local_validation downloads outputs logs wandb conda/envs sim; do
  mkdir -p "${SHARED_ROOT}/${directory}"
done

ENV_FILE="${REPO_ROOT}/.challenge.env"
umask 077
{
  printf '# Generated by scripts/challenge/bootstrap.sh; do not commit.\n'
  printf 'export CHALLENGE_SHARED_ROOT=%q\n' "${SHARED_ROOT}"
  printf 'export CHALLENGE_ENV_NAME=%q\n' "${ENV_NAME}"
  printf 'export CHALLENGE_CONDA_SH=%q\n' "${CONDA_SH}"
  printf 'export CHALLENGE_MODEL_ROOT=%q\n' "${SHARED_ROOT}/models"
  printf 'export CHALLENGE_VLA_REPO_DIR=%q\n' "${SHARED_ROOT}/models/lingbot-vla-v2-6b-robotwin"
  printf 'export CHALLENGE_VLA_MODEL_DIR=%q\n' "${SHARED_ROOT}/models/lingbot-vla-v2-6b-robotwin/checkpoints/global_step_50000/hf_ckpt"
  printf 'export CHALLENGE_QWEN3_DIR=%q\n' "${SHARED_ROOT}/models/Qwen3-VL-4B-Instruct"
  printf 'export CHALLENGE_MOGE_DIR=%q\n' "${SHARED_ROOT}/models/moge-2-vitb-normal"
  printf 'export CHALLENGE_MOGE_CHECKPOINT=%q\n' "${SHARED_ROOT}/models/moge-2-vitb-normal/model.pt"
  printf 'export CHALLENGE_DATASET_ARCHIVE=%q\n' "${SHARED_ROOT}/downloads/robotwin_v21/lerobot_dataset/RoboTwin_lerobot_v21.zip"
  printf 'export CHALLENGE_HF_DATASET_REPO=TianxingChen/RoboTwin2.0\n'
  printf 'export CHALLENGE_HF_DATASET_FILE=lerobot_dataset/RoboTwin_lerobot_v21.zip\n'
  printf 'export CHALLENGE_HF_VLA_REPO=robbyant/lingbot-vla-v2-6b-robotwin\n'
  printf 'export CHALLENGE_HF_QWEN_REPO=Qwen/Qwen3-VL-4B-Instruct\n'
  printf 'export CHALLENGE_HF_MOGE_REPO=Ruicheng/moge-2-vitb-normal\n'
  printf 'export CHALLENGE_TRAIN_DATA=%q\n' "${SHARED_ROOT}/data/train"
  printf 'export CHALLENGE_TRAIN_LIST=%q\n' "${SHARED_ROOT}/data/train/clean_training_data.txt"
  printf 'export CHALLENGE_CLEAN_NORM_STATS=%q\n' "${SHARED_ROOT}/data/train/clean_norm_stats.json"
  printf 'export CHALLENGE_LOCAL_VAL_DATA=%q\n' "${SHARED_ROOT}/data/local_validation"
  printf 'export CHALLENGE_OUTPUT_ROOT=%q\n' "${SHARED_ROOT}/outputs"
  printf 'export CHALLENGE_ROBOTWIN_REVISION=13c3c47ff4312dd62484bcd51be034af55c062d1\n'
  printf 'export CHALLENGE_ROBOTWIN_ROOT=%q\n' "${SHARED_ROOT}/sim/RoboTwin"
  printf 'export CHALLENGE_ROBOTWIN_SIM_ENV_PREFIX=%q\n' "${SHARED_ROOT}/conda/envs/robotwin-sim-13c3c47"
  printf 'export HF_HOME=%q\n' "${SHARED_ROOT}/cache/huggingface"
  printf 'export HF_HUB_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/hub"
  printf 'export HUGGINGFACE_HUB_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/hub"
  printf 'export HF_DATASETS_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/datasets"
  printf 'export HF_ASSETS_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/assets"
  printf 'export HF_XET_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/xet"
  printf 'export TRANSFORMERS_CACHE=%q\n' "${SHARED_ROOT}/cache/huggingface/transformers"
  printf 'export TORCH_HOME=%q\n' "${SHARED_ROOT}/cache/torch"
  printf 'export PIP_CACHE_DIR=%q\n' "${SHARED_ROOT}/cache/pip"
  printf 'export XDG_CACHE_HOME=%q\n' "${SHARED_ROOT}/cache/xdg"
  printf 'export PYTHONPYCACHEPREFIX=%q\n' "${SHARED_ROOT}/cache/pycache"
  printf 'export CONDA_PKGS_DIRS=%q\n' "${SHARED_ROOT}/cache/conda/pkgs"
  printf 'export CONDA_ENVS_PATH=%q\n' "${SHARED_ROOT}/conda/envs"
  printf 'export TMPDIR=%q\n' "${SHARED_ROOT}/tmp"
  printf 'export WANDB_DIR=%q\n' "${SHARED_ROOT}/wandb"
  printf 'export HF_HUB_DISABLE_TELEMETRY=1\n'
  printf 'export TOKENIZERS_PARALLELISM=false\n'
  printf 'export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}\n'
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

challenge_ok "Persistent layout: ${SHARED_ROOT}"
challenge_ok "Runtime environment: ${ENV_FILE}"
printf 'Shared filesystem: '
findmnt -n -o SOURCE,FSTYPE,TARGET -T "${SHARED_ROOT}" 2>/dev/null || printf 'unknown\n'

if (( INSTALL_ENV == 1 )); then
  # shellcheck disable=SC1090
  source "${CONDA_SH}"
  command -v conda >/dev/null 2>&1 || challenge_die 'conda is required for --install-env.'
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  install_args=(--env-name "${ENV_NAME}")
  [[ -z "${FLASH_ATTN_WHEEL}" ]] || install_args+=(--flash-attn-wheel "${FLASH_ATTN_WHEEL}")
  bash "${REPO_ROOT}/tools/create_train_env.sh" "${install_args[@]}"
fi

printf '\nApproved Hugging Face sources:\n'
printf '  dataset: TianxingChen/RoboTwin2.0 :: lerobot_dataset/RoboTwin_lerobot_v21.zip ONLY\n'
printf '  models:  robbyant/lingbot-vla-v2-6b-robotwin\n'
printf '           Qwen/Qwen3-VL-4B-Instruct\n'
printf '           Ruicheng/moge-2-vitb-normal\n'
printf 'Never snapshot-download the full TianxingChen/RoboTwin2.0 dataset (~1.53 TB).\n'
printf '\nNext:\n  source %q\n  bash scripts/challenge/preflight.sh --phase host\n' "${ENV_FILE}"
